// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCik2ZRTpYTP9UvCCgGeufxg4FhYFTeeW8',
    appId: '1:572750917894:web:6e664ebdb01d9c75a12e87',
    messagingSenderId: '572750917894',
    projectId: 'myinfdic',
    authDomain: 'myinfdic.firebaseapp.com',
    storageBucket: 'myinfdic.appspot.com',
    measurementId: 'G-5W43GD75GX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBmvYe-piGMkYHsOmuIwpZlUzv6FheSEt8',
    appId: '1:572750917894:android:aa06af425e6402dca12e87',
    messagingSenderId: '572750917894',
    projectId: 'myinfdic',
    storageBucket: 'myinfdic.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAefGjmTU7D05pBr45BWBTIz6CDO5BIPhY',
    appId: '1:572750917894:ios:ddd24e4c80ddc81ba12e87',
    messagingSenderId: '572750917894',
    projectId: 'myinfdic',
    storageBucket: 'myinfdic.appspot.com',
    iosBundleId: 'com.deatsilence.informationdictionary.infdic',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAefGjmTU7D05pBr45BWBTIz6CDO5BIPhY',
    appId: '1:572750917894:ios:e309f88b98411f2da12e87',
    messagingSenderId: '572750917894',
    projectId: 'myinfdic',
    storageBucket: 'myinfdic.appspot.com',
    iosBundleId: 'com.deatsilence.informationdictionary.infdic.RunnerTests',
  );
}
